MVP-16: 디자인 수정 완성 풀리케 (질문 있음)
Care-Giver/CareGiver pull request #103
Opened 2023-06-03 11:38 UTC by hycv

입력 모달창 (생년월일, 이름, 몸무게 모두 해당) 에서 확인 버튼을 두번 눌러야 하는 문제 : 

첫번째 확인버튼 클릭은 KeyboardAvoidingView 와 연관된, keyboard 를 내리는데 사용된다고 추정됨. 
그래서 두번째 클릭부터 확인 버튼의onPress 함수 작동. 
만약 input 을 다 입력한 후 안드로이드의 키보드 체크버튼을 눌러 키보드를 내리면 확인버튼 한번만 눌러도 작동됨. (다른 방식으로 키보드 내리면 화면에 키보드가 없어도 여전히 두 번 눌러야 함.)

ios device 작동 오류 문제로 안드로이드에서만 확인해 ios 에서도 이런 문제가 발생하는지는 확인못함. 

세 개의 모달에서 모두 같은 문제가 있지만 몸무게 모달에 touch 영역 확인용 console.log 를 달아놓고 주석 처리해 놓았으니 여기서 확인하시는게 더 빠를 것 같습니다!

2023-06-06 11:35 UTC, smnchoi commented
@hycv 현재 코드리뷰 중 입니다. 고생많으셨습니다.
모달 코드에 개선점이 많이 보입니다. 아예 새롭게 [react-native-modal](https://github.com/react-native-modal/react-native-modal) 패키지를 사용하여 리팩토링 할 계획입니다. 새로운 커밋과 브랜치로 피드백 드리겠습니다 🙂

2023-06-06 13:35 UTC, smnchoi commented
> 입력 모달창 (생년월일, 이름, 몸무게 모두 해당) 에서 확인 버튼을 두번 눌러야 하는 문제 :
> 
> 첫번째 확인버튼 클릭은 KeyboardAvoidingView 와 연관된, keyboard 를 내리는데 사용된다고 추정됨. 그래서 두번째 클릭부터 확인 버튼의onPress 함수 작동. 만약 input 을 다 입력한 후 안드로이드의 키보드 체크버튼을 눌러 키보드를 내리면 확인버튼 한번만 눌러도 작동됨. (다른 방식으로 키보드 내리면 화면에 키보드가 없어도 여전히 두 번 눌러야 함.)
> 
> ios device 작동 오류 문제로 안드로이드에서만 확인해 ios 에서도 이런 문제가 발생하는지는 확인못함.
> 
> 세 개의 모달에서 모두 같은 문제가 있지만 몸무게 모달에 touch 영역 확인용 console.log 를 달아놓고 주석 처리해 놓았으니 여기서 확인하시는게 더 빠를 것 같습니다!

@hycv  
해당 문제의 원인은 KeyboardAvoidingView 때문이 아니라, 희영님이 작성하신 잘못된 코드 때문에 그렇습니다.
90dab6ba21a485b3a94a09e84d6cc49d37f71051 커밋의 변경사항을 유심히 보시길 바랍니다.

React 컴포넌트의 Life Cycle 과 언제 컴포넌트에 리렌더링이 일어나는지 좀 더 공부하고 고민해보시길 바랍니다.
이와 관련된 내용은 공식문서에 수록되어 있습니다.

리렌더링에 대한 대원칙입니다.
1. state 가 변하면 리렌더링이 일어납니다
2. prop 이 변하면 리렌더링이 일어납니다.
3. 자식 컴포넌트 (Children Component)의 변화가 생기면 리렌더링 됩니다.

희영님은 키보드 유무에 따른 Modal 의 위치를 조정하기위해 keyboardStatus state 에 종속된 handlePosition 함수를 만들었습니다.
1. keyboardStatus 는 state 입니다. 
2. 키보드의 변화가 일어나면 keyboardStatus 는 변합니다. _- state 가 변하면 리렌더링이 일어납니다._
4. keyboardStatus 가 변하면 handlePosition 리턴값이 변합니다.
5. handlePosition 리턴값이 변하면, `justifyContent: handlePosition()` 때문에 style prop 에 영향을 줍니다. 따라서, style prop 에 연결된 KeyboardAvoidingView 가 리렌더링 됩니다. _- prop 이 변하면 리렌더링이 일어납니다._

즉, _키보드의 움직임이 한 번 변할때마다 코드 내 리렌더링은 두 번 일어납니다._
이를 인지하고 코드를 작성하셨는지 복기해보시길 바랍니다.

KeyboardAvoidingView 컴포넌트가 (거의 동시에) 두 번 변화를 겪을때 다른 event 즉, 터치 이벤트가 발생하면
해당 터치이벤트를 적용하기도 전에, KeyboardAvoidingView 가 리렌더링 됩니다.
그럼 KeyboardAvoidingView 를 자식컴포넌트로 갖고있는 Modal 이 리렌더링됩니다.
따라서, 모달 창을 끄라는 터치이벤트는 적용되기도 전에 무시되므로, 모달창이 꺼지지않는 것입니다.

---
컴포넌트의 리렌더링과 관련된 사안은 React 와 React Native 에서 매우 중요하고 기초적인 지식입니다.
아쉬운 것은, 저와 희영님은 이와 비슷한 주제로 이미 이야기를 나눈적이 있다는 사실입니다.
케어기버에 합류하신지 얼마 안돼셨을때, 유튜브강의를 보며 클론코딩을 하며, 혹은 다른 업무를 하며 이와 관련된 정보를 이미 알려드린적이 있습니다. 작업을 중단하신 몇 주 사이 핵심 지식을 잃어버리신 것 같아 아쉽습니다.

공식문서와 양질의 자료를 정독하셔서, 리렌더링과 관련된 지식을 재정비 하시길 바랍니다 :)

2023-06-06 13:36 UTC, smnchoi requested changes

2023-06-06 13:36 UTC, smnchoi commented on app/components/weight-modal/weight-modal.tsx
> +                {/* //* 위에서 입력한 닉네임 에러 여부에 따라 달라지는 bordercolor, error message */}
@hycv 정규식이 잘못 된 것 같습니다.
9.88 (소숫점 둘째자리까지 기입됨)
980. (소숫점 아래 입력 불가능)
6905 (소숫점 입력불가)
정규식 재확인 부탁드립니다.

2023-06-06 13:45 UTC, smnchoi commented
@hycv 
1. 다른 모달 컴포넌트들도 WeightModal 처럼 react-native-modal 패키지 사용해서 다시 작성해주세요. 
2. CustomInputModal, WeightModal, BirthdayModal 모두 결국 하나의 모달에서 props 만 다르게 하여 구현할 수 있어 보입니다. 최종적으로는, 컴포넌트들을 통합해주세요.

2023-06-06 13:45 UTC, smnchoi requested changes

2023-06-06 13:45 UTC, smnchoi commented on app/components/user-or-pet-profile-info/user-or-pet-profile-info.tsx
>  export const UserOrPetProfileInfo = (props: props) => {
@hycv
props interface 변수명 
UserOrPetProfileInfoProps 로 수정해주세요.

2023-06-06 13:45 UTC, smnchoi commented on app/components/user-or-pet-profile-info/user-or-pet-profile-info.tsx
> +  const { title, profileInfo, showOption, additionalPadding = 20 } = props
@hycv
ES6 문법입니다. 가독성이 좀 더 좋고, default value 를 보다 간단하게 할당할 수 있어서 안전합니다.

2023-06-07 12:06 UTC, hycv commented
정말 자세한 피드백 감사드립니다. 리렌더링의 개념을 알고 있었고, 또 어렴풋하게 이번 키보드 관련 문제가 리랜더링과도 관련이 있을거 같다 고 생각이 들긴 했지만 이걸 어떻게 해결하고 어떻게 적용시킬지 감을 잘 못잡았습니다. 알려주셔서 감사합니다!! 앞으로 개념들을 잘 적용시키기 위해 노력하겠습니다! 코드가 부족하여 오히려 수정하시고 피드백 주시는 과정에서 더 힘드셨을거 같아요. 주신 피드백 잘 보고 또 말씀하신 자료들로 공부하여 좋은 코드를 짤 수 있는 개발자로 성장하도록 하겠습니다!! 💪:face_holding_back_tears:  수정사항 반영은 현재 업무를 우선시 하고 끝낸 뒤에 할까요? 아니면 둘 다 번갈아가면서 해야 할까요?

2023-06-07 12:26 UTC, smnchoi commented
현재업무가 우선순위가 더 높으므로, 현재업무를 먼저 끝내고 수정사항 반영해주세요 🙂

2023-06-15 14:49 UTC, smnchoi commented
@hycv 
테스트빌드 배포를 위해 우선, Merge 진행하겠습니다.
Merge 이후에는 이번 PR 은 닫히게 됩니다.
PR 이 닫히더라도, 기존브랜치 - MVP-16 에서 수정사항 작업해주세요 :)

2023-06-15 14:54 UTC, merged

2023-06-21 08:34 UTC, hycv commented
피드백 주신 부분 최대한 수정하여 커밋 했습니다.
1. react-native-modal 활용해 모달창 수정 했습니다. 
2. 모달창 통합의 경우 useForm Controller 를 다 늘어놓는 통합은 의미가 없을 것 같아 하나의 Controller 를 활용하고 다른 props 로 조절하려고 시도들은 했지만 validate 과 rules 가 너무 다양하여 실패했습니다,,, ㅜㅜ 
3. props interface 변수명 UserOrPetProfileInfoProps 로 수정 완료 했습니다. 
4. weight 모달 정규식, 한자리 숫자에서도 소수점 아래 숫자가 두개 이상이 되면 에러 메세지가 뜨게 수정했습니다.  다만 강아지/고양이의 몸무게가 3자리를 넘어가는 일은 없을 것이라고 생각되어 (세상에서 가장 큰 강아지 종 몸무게가 최대시 100키로 정도 된다고 하더라고요) maxLength 를 4 로 지정해 놓아 980. 이후 소수점이나 네자리 숫자의 경우 입력이 불가능한게 맞는것 같은데 이를 위한 추가 안내 메세지 (몸무게는 최대 99.99키로 까지 입력 가능합니다 와 같은) 를 표시해야 할지에 대한 고민이 필요할것 같습니다.

2023-06-21 09:13 UTC, smnchoi commented
고생하셨습니다. 내일까지 확인하겠습니다 🙂