Mvp 23 예약 신청 스크린
Care-Giver/CareGiver pull request #113
Opened 2023-06-23 17:03 UTC by beom-i

MVP-23 예약 신청 스크린 작업 완료

2023-06-24 04:42 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
@beom-i
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/ecb96db1-0a2d-4187-be69-f987ce6b926a)
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/38d10e73-9cd3-4ff4-bc4b-31bdfbd5c528)

입력을 위해 키보드가 표출되면 input 창을 가립니다.
키보드가 보여지면 자동으로 스크롤이 되게 수정해주세요. input 찾을 가리지 않게요 :) 
(ios 시뮬레이터 상에서, `command + k` 클릭시 소프트웨어 키보드가 표출됩니다.)

2023-06-24 06:43 UTC, smnchoi requested changes

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +  const firstClick = (click: string) => {
`click: string` 대신, Type 을 보다 더 명시해주세요.
`click: "없음" | "치즈" | "닭고기"` 으로 수정해주세요.

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +      //없음일때 또 누르면 취소되면 좀 그럴 것 같습니다.
잘 하셨습니다 :) 주석 지워주세요.

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +  const secondClick = (click: string) => {
마찬가지로, click type 수정해주세요.
아래에있는 thirdClick 의 click 또 마찬가지로 수정해주세요.

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +        <View style={{ marginTop: 24, marginBottom: 16 }}>
View 로 굳이 감싸지 않아도, margin 을 줄 수 있습니다. 
View 삭제하고, 안에 있는 컴포넌트들의 margin 을 수정해서 구현해주세요.
최대한 컴포넌트들을 less nested 하게 구현하는게 좋습니다.

2023-06-24 06:43 UTC, smnchoi commented on app/components/place-holder-input-box/place-holder-input-box.tsx
> +  placeholdertext: string
camelCase 로 다시 써주세요. placeholderText

2023-06-24 06:43 UTC, smnchoi commented on app/components/place-holder-input-box/place-holder-input-box.tsx
> +  boxheight: number
boxHeight

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +            <ClickToBlueButton
Child 컴포넌트가 안 쓰이면, 굳이 이렇게 쓰지 않고 
self-closing 태그로 쓰는게 더 보기 좋습니다.

    <ClickToBlueButton
        buttonText={"없음"}
        buttonHeight={45}
        buttonWidth={115}
        isActiving={is없음Active}
        onPress={() => firstClick("없음")}
    />

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +        <View style={{ marginTop: 16 }}>
불필요한 View

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +        <TouchableOpacity
UI 통일감을 위해 Pressable 로 수정해주세요.
(기본적으로 버튼은 Pressable 로 하고, 예외적인 경우 - 터치피드백이 꼭 필요한경우 - 에만 TouchableOpacity 를 사용하도록 합니다.)

2023-06-24 06:43 UTC, smnchoi commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +      <TouchableOpacity
~~Pressable~~
이건 TouchableOpacity 로 하는게 UI 가 더 낫네요.
TouchableOpacity 유지해주세요!

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +          style={{
StyleSheet 만들어서 따로 styles 로 빼주세요. 이 style 은 inline 으로 주기에는 너무 기네요.

2023-06-24 06:43 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +  // To. 수민님 이부분을 강아지, 처음엔, 되도록 셋다 한번에 useEffect에 넣고 싶었는데, 우선순위 때문에 한 곳에 멈추는 경우가 있어서.. 따로 했습니다..
2번쨰 버튼 그룹은, 굳이 세 개의 useState 가 따로 있을 필요가 있을까요?
다른 그룹들과는 달리, 어차피 세 개 중 하나만 선택될테인데 말이죠.
하나의 useState 로 묶으면, useEffect 훅 없이 더 간단하게 구현할 수 있습니다.

[78bea33](https://github.com/Care-Giver/CareGiver/pull/113/commits/78bea3372ab35eb81b8dd454f036e9c511ff7490)

2023-06-24 06:43 UTC, smnchoi commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +  isActiving: boolean
prop 들 전부 설명 추가해주시길 바랍니다. 간단하게라도 꼭 적어주세요

2023-06-24 06:43 UTC, smnchoi commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +  const buttonStyle = {
type 명시해주세요.
const buttonStyle: ViewStyle = ...

2023-06-24 06:43 UTC, smnchoi commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +  const [isActive, setIsActive] = useState(isActiving)
지금처럼 prop value 로 state 의 initial value 를 지정해줄때는,
prop 의 default value 를 지정해주는게 좋습니다.
`isisActiving = false`

[참고]
- https://react.dev/learn/thinking-in-react#step-3-find-the-minimal-but-complete-representation-of-ui-state
- https://react.dev/learn/you-might-not-need-an-effect

## To be aware of when initializing the initial state of useState with a prop value:

Prop changes: Keep in mind that the initial state set by useState is only used when the component is initially rendered. If the prop value passed to the component changes after the initial render, it won't automatically update the state. To handle prop changes and update the state accordingly, you can use the useEffect hook with the prop value as a dependency.

Unidirectional data flow: React follows a unidirectional data flow, which means that data flows from parent components to child components through props. If the initial state value is passed as a prop, it should be owned and controlled by the parent component. The child component should treat it as a read-only value and not modify it directly. If the child component needs to modify the state, it's generally recommended to lift the state up to the parent component and pass down the state value and a callback function as props.

Default value: If the prop value is optional or not always provided, you can provide a default value or handle the absence of the prop gracefully. You can use default prop values or conditional logic to handle cases where the prop value is not available.

Component reusability: Initializing the state with a prop value can make your component more reusable, as it allows different initial states to be passed from parent components. However, keep in mind that the component's logic should not rely solely on the initial state provided by the prop. It's a good practice to handle state updates and modifications within the component itself, rather than relying solely on the initial prop value.

By considering these points, you can effectively use useState with prop values to initialize the initial state of your components in a controlled and predictable manner.

2023-06-24 06:50 UTC, smnchoi commented
@beom-i 코드리뷰 드렸습니다. 피드백 반영해서 수정해주세요 🙂

2023-06-24 06:53 UTC, smnchoi commented
@beom-i 
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/f1fcfc77-bc74-441e-9371-7de2e767b9fe)

안드로이드에서는 input 의 placeholder 가 전부 위치가 이상하네요.
디자인보다 더 밑에 위치합니다. 개발 하실때 꼭 안드로이드랑 ios 시뮬레이터 둘 다 켜서
두 플랫폼 모두 동시에 확인하면서 개발 진행해주세요. RN 은 하이브리드 앱 플랫폼입니다.

2023-06-24 07:22 UTC, beom-i commented
코드리뷰 해주셔서 감사합니다 수민님 🙂 !! 최대한 오늘까지 틈내서 해보겠습니다. 안되면 내일까지는 무조건 다시 해서 올리겠습니다. 감사합니다 !

2023-06-24 07:33 UTC, beom-i commented on app/screens/make-booking/make-booking-screen.tsx
> +        <View style={{ marginTop: 24, marginBottom: 16 }}>
이 부분에 대해서 여쭤보고 싶었던 게 있었습니다. 
View라는 것이 한 뭉탱이로 볼 때, 코드가 정리된다는 (?) 느낌을 주기 위해 한 뭉탱이 마다 View를 했습니다.. 
안 그러면 이해할 때, 쉽지 않더라구요.. 그래서 몇번째라는 주석처리도 다 해둔건데 리액트 네이티브에서는 어떤 것이 더 효율성(?)있게 선호하나요 ?

2023-06-24 07:38 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +        <View style={{ marginTop: 24, marginBottom: 16 }}>
View 는 정리용으로 쓰이는게 아닙니다. 특정한 style 을 주어야 할때 쓰이죠. 이미 기본적으로, ScreenRootView 도, ScrollView 도 View 를 내포하고 있는 요소입니다.
가장 효율적인 코드는

1. 읽기 편하며
2. 불필요한 컴포넌트가 없는

코드입니다.
코드는 감싸지면 감싸질 수록 (Nesting) 읽기 어려워 집니다. 해당 경우에는 flexDirection 이나, backgroundColor 등 한꺼번에 View style 을 바꿀일 이 있던게 아니라, 그저 margin 만 필요한 상황이었습니다. 그리고, 이러한 margin 은 child 컴포넌트의 style 만으로도 구현 가능했습니다. 따라서, 이러한 상황에서의 View 는 불필요한 컴포넌트입니다.

2023-06-24 07:39 UTC, beom-i commented
특정한 style을 주어야 한다는 말씀을 보고 확 이해 되었습니다. 맞습니다.. margin으로 충분히 가능하지만, 뭔가 서로 다른 컴포넌트에 아무 규칙 없이 margin을 주면 혼란스럽지 않을까 생각했었는데 말씀해주셔서 확실히 이해되었습니다. 감사합니다 !!

2023-06-24 14:02 UTC, beom-i commented on app/screens/make-booking/make-booking-screen.tsx
> +  // To. 수민님 이부분을 강아지, 처음엔, 되도록 셋다 한번에 useEffect에 넣고 싶었는데, 우선순위 때문에 한 곳에 멈추는 경우가 있어서.. 따로 했습니다..
이 코드 보고 무릎을 치고 유레카 외쳤습니다..... 감사합니다.

2023-06-24 14:04 UTC, beom-i commented on app/screens/make-booking/make-booking-screen.tsx
> +          style={{
이 부분도 옛날부터 계속 여쭤보고 싶었는데, 오늘 질문이 너무 많아 죄송하지만 여쭤보겠습니다.
Screen 같은 경우는 기존 코드들 보면 다 style.ts로 빼는 경향이 있고, 컴포넌트는 내부에 stylesheet를 정하는데 혹시 이것이 법칙이 있을까요?

2023-06-24 14:04 UTC, beom-i commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +  const [isActive, setIsActive] = useState(isActiving)
> prop value 로 state 의 initial value 를 지정해줄때외에는 initaial value를 지정하지 않아도 될까요 ?
> 물론, 이번 컴포넌트에서 Placeholder의 텍스트같이 보여지는 것은 하는것이 좋아보입니다.
> 부모에서 무조건 props를 전달해야하는 부분 외에는 지정하는 것이 좋아보이긴 합니다. 혹시 이 부분 어떻게 사용될까요 ?

2023-06-24 14:05 UTC, smnchoi commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +  const [isActive, setIsActive] = useState(isActiving)
대부분의 경우, prop 의 initial value 를 지정해주는 것이, 지정해주지 않는 것 (undefined) 보다 낫습니다. 정해진 것은 없습니다. 맥락에 따라 다릅니다.

2023-06-24 14:06 UTC, beom-i commented on app/components/click-to-blue-button/click-to-blue-button.tsx
> +  const [isActive, setIsActive] = useState(isActiving)
아 그렇군요. 나머지도 지정하겠습니다. 감사합니다 :)

2023-06-24 14:07 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +          style={{
Prettier 로 formatting 했을때, inline style 코드가 4줄이상 길어지면 전부 styles 로 따로 빼주면 됩니다 🙂

2023-06-24 14:17 UTC, beom-i commented on app/screens/make-booking/make-booking-screen.tsx
> +          style={{
넵 알겠습니다 :) 바쁘신데 답변주셔서 감사합니다 !

2023-06-25 12:57 UTC, smnchoi requested changes

2023-06-25 12:57 UTC, smnchoi commented on app/components/place-holder-input-box/place-holder-input-box.tsx
> +  /* 입력하기 전에 연하게 적혀져 있는 Text를 props로 추가하여 사용할 수 있습니다. */
TS 에서 documentation 주석은 이게 아니라.

```
 /**
   * 주석 내용
   */
```

이거입니다.

2023-06-25 12:57 UTC, smnchoi commented on app/components/place-holder-input-box/place-holder-input-box.tsx
> +            style={[styles.input, { height: boxHeight }]}
`TouchableWithoutFeedback` 은 [공식문서](https://reactnative.dev/docs/touchablewithoutfeedback)에도 나와있듯이, 사용을 지양하는 컴포넌트입니다.
`Pressable` 로 교체하세요.

<img width="872" alt="image" src="https://github.com/Care-Giver/CareGiver/assets/70505699/f3827d22-572a-4922-99df-0c4d8f350490">

2023-06-25 13:34 UTC, beom-i commented on app/components/place-holder-input-box/place-holder-input-box.tsx
> +            style={[styles.input, { height: boxHeight }]}
아 넵 이 부분은 제가 구글링으로 키보드 입력창 가리는 것 해결하다가 넣었습니다. 빼겠습니다. :)

2023-06-25 13:39 UTC, smnchoi commented on app/screens/make-booking/make-booking-screen.tsx
> +      <Pressable style={styles.pressableContainer} onPress={checkbuttonPress}>
@beom-i
키보드가 보여지면, 이 버튼을 안 보이게 해주세요.
useKeyboard 훅을 사용하면 도움이 될껍니다 :)

2023-06-25 14:54 UTC, smnchoi commented
시간차가 발생하면, Keyboard 컴퍼넌트와 addListener 메서드, `keyboardWillShow` 를 사용해보세요.
[https://reactnative.dev/docs/keyboard](https://reactnative.dev/docs/keyboard)

2023-06-25 16:25 UTC, beom-i commented
➕ Pushed commit: [MVP-23 [코드리뷰] keyboard 사용할 때, 확인 버튼 사라지게 하기 (ios, android 다르게 구현 android는 에뮬레이터 상으로 늦게 생성되고 사라지는 현상 발생)](https://github.com/Care-Giver/CareGiver/pull/113/commits/a174486e36b73e52cc7f2784f54e6f3130de8f06)

2023-07-01 07:40 UTC, smnchoi commented
@beom-i @smnchoi 

**[TODO]**
- 안드로이드에서 소프트웨어 키보드 표출시, 확인 버튼이 사라지는데 딜레이 발생 ➡️ 아직 수정 안됨
- KeyboardAvoidingView 대신 Keyboard _AwareScroll_ View 로 교체
- (시간이 된다면)
    - payment-request-screen 을 참고하여 make-booking-screen  type 들 수정해야함

2023-07-01 07:54 UTC, smnchoi commented
@beom-i
이런 boolean 조건 판단하는 로직은 렌더링 블럭 (return 블럭) 안에 쓰지말고
바깥에 따로 쓰세요.
[image.png](https://files.slack.com/files-pri/T035QQ6AYK0-F05F5719FB4/image.png)
[image.png](https://files.slack.com/files-pri/T035QQ6AYK0-F05FHRK9QUR/image.png)

2023-07-01 07:57 UTC, beom-i commented
넵 알겠습니다 🙂

2023-07-01 07:58 UTC, merged