Mvp 22/결제 스크린
Care-Giver/CareGiver pull request #115
Opened 2023-06-24 13:18 UTC by hyeri1126

리뷰요청

1. width="100%"를 사용하였으나 화면 양쪽에 약간 여백이 있음.
2. floating되어 있는 버튼을 참고하라고 한 코드를 참고하지 않고 CSS로 위치를 고정시킴. (왜 애니메이션 효과를 적용하는지 모르겠음)
3. '결제수단은 독립된 컴포넌트로써 분리하여 만들 것' -> css로 위치, 디자인만 입히고 버튼이 눌리는 독립된 컴포넌트로써 구현하지 못 함.

2023-06-25 14:06 UTC, smnchoi requested changes

2023-06-25 14:06 UTC, smnchoi commented on app/components/payment-tool/payment-tool.tsx
> +      <Pressable style={styles.content}>
@hyeri1126
이 글 참고해서, 클릭했을때 스타일 바뀌게 변경하세요.
https://stackoverflow.com/questions/45478621/react-native-styling-with-conditional

2023-06-25 14:06 UTC, smnchoi commented on app/components/payment-tool/payment-tool.tsx
> +    marginRight: 11,
margin 은 여기다가 넣는게 아닙니다.
참고 - margin 과 padding 의 차이: https://stackoverflow.com/questions/5958699/difference-between-margin-and-padding

PaymentTool 컴포넌트 끼리 간격을 만들고 싶으시면, 여기에있는 marginRight 는 제거하고,
payment-screen 에서, 이 컴포넌트에 style prop 으로 marggin 을 넘겨서 간격을 만드세요.

2023-06-25 14:06 UTC, smnchoi commented on app/components/payment-tool/payment-tool.tsx
> +  tool: string
애매하게 string 이 아니라, 보다 더 명확하게 바꿔주세요.
`tool: "카카오페이" | "네이버페이" | "토스"`

2023-06-25 14:06 UTC, smnchoi commented on app/components/payment-tool/payment-tool.tsx
> +    // 5~6번까지는 콘솔창에서 클릭된 tool이 잘 반영되는데 그 이후로는 클릭해도 반영이 안돼요(콘솔창에 뜨지 않음)....ㅠㅠ 왜이러는걸까요??
"클릭된" tool 이 반영된게 아니라,
line 44 에 있는 console.log(selectedTool) 
이 코드가 여러번 실행된 것입니다.

애초에 console.log(selectedTool) 는 onPaymentToolPress 함수 블럭 안에 있지 않기 때문에,
클릭과는 아무런 연관관계가 없습니다.

React, ReactNative 에서 코드가 어떤 순서로 실행되는지 유념하여 작업하시길 바랍니다.
참고 - Lifecycle: https://luehdigitalmedia.com/react-and-react-native-lifecycle-how-react-native-works/

2023-06-25 14:06 UTC, smnchoi commented on app/components/payment-tool/payment-tool.tsx
> +    // 클릭시, 버튼 안에 작은 원을 만들고 싶은데 이것도 안되네요 ㅠㅠ!!
클릭 상태일시, TouchableOpacity 스타일링을 바꾸면 됩니다.

그런데 그냥, Image 컴포넌트로 대체하고, 클릭여부에 따라 이미지를 바꿔주세요.
radio_active 와 radio_inactive 이미지 참고 바랍니다.

2023-06-25 14:06 UTC, smnchoi commented on app/components/payment-tool/payment-tool.tsx
> +          <PreBol14 text={tool} color="#797979" />
클릭전에는 `PreReg14` 이고, 클릭된 상태에서만 `PreBol14` 입니다. (색상도 바뀌어야함)

2023-06-25 14:28 UTC, hyeri1126 commented
코드리뷰 확인했습니다. 수정해보겠습니다!

2023-06-26 11:10 UTC, smnchoi commented on app/screens/payment/payment-screen.tsx
> +    backgroundColor: "#00196C",
@hyeri1126 
따로 상수 처리되어있지 않는 색상이 있다면, 그대로 사용하지말고 디자이너님께 문의하세요. 케어기버 앱 내에서 색상은 항상 정해진 상수로 지정해줘야 합니다! Hexa 값으로 입력하지 말아주세요.

2023-06-26 16:10 UTC, hyeri1126 commented on app/screens/payment/payment-screen.tsx
> +    backgroundColor: "#00196C",
넵!  Hexa 값 사용은 지양하도록 하겠습니다.

2023-07-01 12:25 UTC, merged