Mvp 13
Care-Giver/CareGiver pull request #117
Opened 2023-06-25 14:08 UTC by bongbong811

1. 표기법 변경
2. 위치 권한 체크 및 요청
3. 주소 검색 화면 -> 주소 맵 화면 (지번은 맵에  따라 변형이 되나, 주소명은 초기 값이 고정되는 문제)

2023-06-25 14:09 UTC, smnchoi commented
고생하셨습니다 영묵님. 앞선 PR 들이 있어서, 자정을 조금 넘겨서 코드리뷰 완료할 것 같습니다. 고생많으셨습니다!

2023-06-25 14:41 UTC, smnchoi commented
API 키 교체는 MVP-21 에서 진행되었습니다. [https://github.com/Care-Giver/CareGiver/commit/ebcda750327df040067f499f608fa2331ff9163a](https://github.com/Care-Giver/CareGiver/commit/ebcda750327df040067f499f608fa2331ff9163a)


MVP-21 ➡️ MVP-13 merge 먼저 진행하겠습니다.

2023-06-25 15:08 UTC, smnchoi commented
@bongbong811 
안드로이드 빌드가 되질 않습니다. 에러 로그 상으로는 `react-native-geocoder` 셋업이 덜 된 것 같은데,
작업하실때 안드로이드에서 별 문제 없으셨나요?


```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/react-native-geocoder/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':react-native-geocoder'.
> Could not find method compile() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/react-native-geocoder/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':react-native-geocoder'.
> Could not find method compile() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 5s

    at makeError (/Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/execa/index.js:174:9)
    at /Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/tedchoi/Documents/GitHub/_CareGiver/CareGiver/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2023-06-25 15:20 UTC, smnchoi requested changes

2023-06-25 15:20 UTC, smnchoi commented on app/screens/cg-set-address/cg-set-address-screen.tsx
>    const createMarker = (coordinate) => {
# 줌인 상태에서 다른 위치를 클릭하면, 줌인이 풀려버립니다.
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/0fa29e9c-d120-4ea9-8795-db32171f37dd)
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/3a0e4c57-968e-46a0-a724-bf22bde2c1cd)
- createMarker 이 함수가 영향을 주는 것 같습니다.
- 함수 내에서 여러개의 state - markers, createdMarker, initialRegion 들이 바뀌게 되는데 이들의 변화가 MapView 를 다시 리렌더링 시켜서 줌인이 풀리는 것 같습니다.
- 줌인이 풀리는 것을 방지하기 위해, 의도치 않은 리렌더링을 방지해주세요. useMemo, useCallback, useRef 훅을 사용하시면 도움이 되실 껍니다 :)

# (기타) Marker 이미지가 바뀌었네요. images.map_marker 으로 다시 복구해주세요.

2023-06-25 23:11 UTC, bongbong811 commented
아~ geocoder는 테스트할때만 사용했던 라이브러리라 삭제하겠습니다! 줌인 상태체크는 다시한번봐볼게요!

2023-06-25 23:28 UTC, smnchoi commented
네 감사합니다. 라이브러리 설치하기전에 꼭 설치용 브랜치만 따로 만들어서, 설치 때 만들어진 변경사항들을 독립된 커밋으로 분리해주세요. 

이번 PR에도 여러 라이브러리가 설치되었는데 한 커밋에 변경사항이 다 섞여있어서, 어느 변경사항이 라이브러리 설치에 의한것인지 구분이 어려웠습니다. 라이브러리는 서로 버전 의존성이 있기 때문에 한번 깨지면 복구하기 정말 시간이 많이 들어요. 예전부터 협업하면서 많이 겪었던 문제라, 꼭 부탁드립니다 🙏

2023-06-25 23:42 UTC, bongbong811 commented
헉 mvp-13 브랜치에서 설치했는데 요번에도 섞여있었나요 ㅠㅠㅠㅠ

2023-06-25 23:43 UTC, bongbong811 commented
geocoder 라이브러리는 삭제하니깐 안드로이드 빌드 정상적으로 동작하는거 확인했습니다!

2023-06-25 23:45 UTC, bongbong811 commented
설치 & 커밋을 제가 뭔가 잘못하고 있는 것 같은데 회의때 한번 여쭤볼게요~

2023-06-25 23:47 UTC, smnchoi commented
빌드 이슈 확인해주셔서 감사합니다 :+1: 

네 언제든지 말씀주세요 ☺️ 
이 커밋에, 주소세팅화면 로직 코드 뿐만 아니라 설치관련 변경사항이 섞여 있어서 그렇습니다 ㅠㅠ (둘은 분리되어야 합니다)

[https://github.com/Care-Giver/CareGiver/commit/e80a25431a0a313772c0d18ab0d35351dbda1d78](https://github.com/Care-Giver/CareGiver/commit/e80a25431a0a313772c0d18ab0d35351dbda1d78)

2023-07-02 12:55 UTC, smnchoi commented
https://github.com/Care-Giver/CareGiver/pull/125

2023-08-27 01:32 UTC, smnchoi commented
develop 브랜치로 Merge 완료 - 64cdd220746d607d3e0ec1efedbecaafc580b98c

2023-08-27 01:32 UTC, closed without merging