MVP - 24 예외처리 및 interface 변수명 수정
Care-Giver/CareGiver pull request #123
Opened 2023-07-02 07:35 UTC by hojkim77

수정사항
1. [app/services/axios/confirmed-bookings.ts]
    interface명 수정
2. [app/components/booking-list/booking-list.ts]
    피드백시 첨부된 스크린샷의 null에 관한 예외처리 추가
    (피드백 댓글에서는 [../m.../manage-booking-screen.tsx] 경로를 태그해주셨는데, 해당 부분에서는 예외처리를 할 방법이 떠오르지 않아, components에서 에러가 발생한다고 생각하여 booking-list.ts에서 예외처리 진행했습니다.)

2023-07-02 13:13 UTC, smnchoi requested changes

2023-07-02 13:13 UTC, smnchoi commented on app/components/booking-list/booking-list.tsx
> +  React.useLayoutEffect(() => {
@hojkim77
리액트 아키텍쳐를 좀 더 공부하시길 바랍니다.
booking-list 가 child,
manage-booking-screen 이 parent 컴포넌트입니다.

booking-list 는 bookings prop 데이터가 정상적이어야 작동하는 컴포넌트입니다.
이를 통제하는것은 prop 을 넘겨주는 주체인 parent 컴포넌트에서 하는 게 더 적절합니다.
(왜 그러한 지는, prop 의 개념이 생긴 이유를 공식문서를 보면서 고민해보세요.)
따라서 제가 manage-booking-screen 에서 제어하라고 요청드린 것입니다.

booking-list 에 있는 로직들은 전부 manage-booking-screen 에서 이뤄져야 합니다.

2023-07-02 13:15 UTC, smnchoi commented
@hojkim77 
manage-booking-screen 을 다음과 같이 수정하여 bookings 가 비정상적일 경우를 제어하세요
```
...
export const ManageBookingScreen: FC<
  StackScreenProps<NavigatorParamList, "manage-booking-screen">
> = observer(function ManageBookingScreen() {
  // MST store 를 가져옵니다.
  // const { someStore, anotherStore } = useStores()

  // 필요시, useNavigation 훅을 사용할 수 있습니다.
  // const navigation = useNavigation()
  const [bookings, setBookins] = useState([])
  const {
    ConfirmedBookingsModel: { setAllconfirmedBookings, confirmedBookings },
  } = useStores()
  useLayoutEffect(() => {
    setAllconfirmedBookings()
    setBookins(confirmedBookings)
    //console.log(bookings[0])
  }, [])

 const hasBookings = bookings.length > 0

  return (
    <ScreenRootView testID="ManageBooking">
      <BookingCheckButton style={{ zIndex: 1 }} bookingCount={2}></BookingCheckButton>
      { hasBookings ? <BookingList bookings={bookings} /> : <PreReg12 text="예약이 존재하지 않습니다"/> }
    </ScreenRootView>
  )
})
```

2023-07-02 13:16 UTC, smnchoi requested changes

2023-07-02 13:16 UTC, smnchoi commented on app/components/booking-list/booking-list.tsx
> +  bookings?: ConfirmedBookings[]
required prop 으로 바꾸세요. prop 주석을 달아주세요
```suggestion
  bookings: ConfirmedBookings[]
```

2023-07-02 13:20 UTC, hojkim77 commented
해당 부분들 명심하겠습니다.

다른 컴포넌트 참고해서 prop 설명 달아놓겠습니다.

2023-07-02 13:28 UTC, hojkim77 commented
@smnchoi
실제로 예약이 없는 경우에 대한 디자인을 디자인팀에게 요청해야할까요?

2023-07-02 13:32 UTC, smnchoi commented
네 그런경우를 엠티뷰 (empty view) 라고 합니다.
<channel_id:C03EF9257C1> 채널에 글 작성해주세요 🙂

2023-07-02 13:47 UTC, hojkim77 commented
디자인 받은 후 마무리하여 풀리퀘스트 보내겠습니다!

2023-07-02 14:18 UTC, smnchoi commented
새 풀리퀘스트 안만드셔도 됩니다.

2023-07-03 09:25 UTC, hojkim77 commented
@smnchoi
엠티뷰 디자인 확인했습니다. 이 때 screen에서 null 처리를 하기 때문에 빨간 박스 안의 컴포넌트를 사용하기 힘들 것 같습니다. 이러한 경우에 이 부분은 없이 구현해도 괜찮을까요?

추가적으로 해당 스크린은 예약이 아예 없을 경우에 나오는 스크린이므로 달력(날짜) 표기가 무의미하다고 생각하기도 했습니다!
[image.png](https://files.slack.com/files-pri/T035QQ6AYK0-F05FN6P73NV/image.png)

2023-07-12 09:29 UTC, smnchoi commented
@hojkim77 네 달력 날짜 표기없이 엠티뷰 디자인 적용해서 커밋 푸시 해주세요 🙂

2023-07-14 04:46 UTC, smnchoi commented
@hojkim77 호중님, 일단 지금까지 작업물 merge 하겠습니다.
이후 작업물은 새로 풀리퀘스트 만들어주세요 🙂

2023-07-14 05:02 UTC, smnchoi commented on app/components/booking-list/booking-list.tsx
>    props.bookings.map((item, idx) => {
@hojkim77 
map 콜백함수에는 리턴 밸류가 있어야 합니다.
리턴 밸류가 없다면, forEach 를 쓰는게 더 적절합니다.
```
bookings.forEach((item, idx) => {
  console.log(item.services);
  const dataprop = {
    name: item.name,
    serviceType: "creche",
    petname: item.pets[0].name,
    species: item.pets[0].species.name,
    petservices: item.services,
    address: item.address,
    time: item.startTime,
    height: 50,
    day: item.startTime.substring(0, 10),
  };
  const newData = { title: String(idx), data: [dataprop] };
  sections.push(newData);
});
```

2023-07-14 05:21 UTC, hojkim77 commented
피드백 감사합니다🙂

2023-07-14 07:02 UTC, merged