Mvp 40/회원가입 플로우
Care-Giver/CareGiver pull request #149
Opened 2023-08-21 06:18 UTC by hojkim77

총 3개의 스크린 구현

1. TermsOfServiceScreen
약관 동의 스크린입니다.
- 주요코드
    - 동의 체크박스 : 각 동의버튼 두개와 모두동의버튼 한개로 이루어져 "다음"버튼 활성화에 관련된 간단한 로직 추가
    - 노션페이지이동

2.  RegisterScreen
회원가입시 필요한 내용을 입력하는 스크린입니다.
- 주요코드
    - validation
        각 입력값 따로 validation 추가했습니다. 
        인증번호는 어떠한 값으로 넘어올지 몰라 "숫자로 10글자까지"로 제한히였습니다.
3.  RegisterSuccessScreen

2023-08-21 06:35 UTC, smnchoi commented
@hojkim77 
PR 생성해주신 것 확인하였습니다. 빠르면 오늘 밤, 늦어도 내일까지 리뷰 완료하도록 하겠습니다. 고생하셨습니다 호중님, 기여해주셔서 감사합니다 ☺️

2023-08-21 07:28 UTC, smnchoi commented
@hojkim77 스크린 파일들은 있는데, `app-navigator.tsx `에서 스크린 컴포넌트들이 셋업이 안 되어 있습니다. 작업하실때는 어떻게 스크린으로 이동해서 작업하셨나요? 저도 코드리뷰때에는 직접 작업하신 스크린으로 이동해서 테스트해야 하기때문에,  만들어주신 스크린 컴포넌트들을 `app-navigator.tsx` 에 추가해주세요 :)

2023-08-21 08:21 UTC, hojkim77 commented
> @hojkim77 스크린 파일들은 있는데, `app-navigator.tsx `에서 스크린 컴포넌트들이 셋업이 안 되어 있습니다. 작업하실때는 어떻게 스크린으로 이동해서 작업하셨나요? 저도 코드리뷰때에는 직접 작업하신 스크린으로 이동해서 테스트해야 하기때문에, 만들어주신 스크린 컴포넌트들을 `app-navigator.tsx` 에 추가해주세요 :)

homescreen부분을 바꿔가며 작업하다보니 일부러 커밋을 안남겼는데 그러면 스크린이 추가가 안되는걸 생각 못했네요,,!
이런경우에는 test를 위해 잠시 바꿨던 homescreen부분 원래대로 돌리고 스크린 추가한 상태로 커밋하면 될까요?

2023-08-21 08:23 UTC, smnchoi commented
네 그렇게 해주시면 됩니다 🙂

2023-08-22 08:07 UTC, smnchoi commented
@hojkim77 
> homescreen부분을 바꿔가며 작업하다보니...

호중님, 이게 무슨 말씀이신지 더 자세히 말씀해주실 수 있나요? 이번 업무 진행하실때 어떻게 작업하고계셨나요??

2023-08-22 08:12 UTC, hojkim77 commented
> @hojkim77
> 
> > homescreen부분을 바꿔가며 작업하다보니...
> 
> 호중님, 이게 무슨 말씀이신지 더 자세히 말씀해주실 수 있나요? 이번 업무 진행하실때 어떻게 작업하고계셨나요??

3가지 스크린을 만들면서 3개 모두 navigator상 homescreen에 넣어서 화면 확인하면 작업했다는 뜻이었습니다!

2023-08-22 08:30 UTC, smnchoi commented
아하~ 이해했습니다. 다음 회의 때 Navigator 에 관하여 설명 드리겠습니다 :) 
이번 작업하시느라 고생많으셨습니다 🙏🏻

2023-08-24 04:58 UTC, smnchoi commented on app/screens/terms-of-service/terms-of-service-screen.tsx
> +        //TODO bottom position을 어떻게 줘야할지 피드백 주시면 감사하겠습니다.
@hojkim77
이 버튼처럼 고정된 위치에 존재하는 컴포넌트는
position: "abosolute" 를 사용하는 것이 더 편합니다.
```
style={{ position: "absolute", bottom: BOTTOM_HEIGHT, alignSelf: "center" }}
```
(제가 수정했으니, 별도로 커밋 안남기셔도 됩니다 :) )

2023-08-24 10:23 UTC, smnchoi requested changes

2023-08-24 10:23 UTC, smnchoi commented on app/components/register-text-input/register-text-input.tsx
> +  title: string
string 말고 더 명시적인 것으로 바꿔주세요.

```suggestion
  title: "휴대폰 번호" | "닉네임(필수)" | "생년월일" | "인증번호"
```

2023-08-24 10:23 UTC, smnchoi commented
@hojkim77 
# 변경요청
## 1. "필수 약관 모두 동의" 만 체크하더라도, "다음" 버튼 클릭 가능해야 합니다.
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/5b4c3f0a-d19e-4ec5-935c-50e276cb5333)

## 2. 타입스크린트 잘못 사용하고 있습니다. 회의끝나고 호중님 VSCode 한번 확인해봐야겠네요.
```
type Sex = {
  MALE: "MALE"
  FEMALE: "FEMALE"
}
...
const [sex, setSex] = useState<Sex>(null)
```
<img width="819" alt="image" src="https://github.com/Care-Giver/CareGiver/assets/70505699/eb25176c-1e4e-42fc-bac6-fe71fcde5abc">

## 3. 호중님 VSCode 에서는 eslint 가 작동하고 있지 않나요? (switch 문법에 break 가 빠졌네요)
<img width="708" alt="image" src="https://github.com/Care-Giver/CareGiver/assets/70505699/3469a797-cfe1-40f2-be0e-74da5b5c27c9">

## 4. 생년월일과 휴대폰 번호 작성했다가, 다시 지우고 작성하면 고장납니다. 고쳐주세요.
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/13ed82a8-b90d-4919-8048-ed111c9ef903)

2023-08-27 02:02 UTC, smnchoi commented
# 잘못된 예외처리
@hojkim77 선택약관만 동의했는데도, "모두 동의" 때문에 "다음" 버튼이 활성화 되는 문제가 있습니다. 제가 수정했으니, [f86bfbb](https://github.com/Care-Giver/CareGiver/pull/149/commits/f86bfbb0075372e2dbe64519c3c62d3f347a83b8) 커밋 참고해주세요.
<img width="395" alt="image" src="https://github.com/Care-Giver/CareGiver/assets/70505699/7f68a2a8-f158-4b18-8cb3-7642fcbf6be3">

2023-08-27 02:38 UTC, smnchoi commented
# 잘못된 키보드 처리
소프트웨어 키보드가 "휴대폰 번호" 와 "인증번호" 필드를 가립니다.
<img width="395" alt="image" src="https://github.com/Care-Giver/CareGiver/assets/70505699/9c99a024-3ac5-408c-a3b5-fbabe98d6b3f">
<img width="418" alt="image" src="https://github.com/Care-Giver/CareGiver/assets/70505699/bbfd7bc9-7e29-44a1-a490-1da99b142ada">

2023-08-27 07:26 UTC, hojkim77 commented
> # 잘못된 예외처리
> @hojkim77 선택약관만 동의했는데도, "모두 동의" 때문에 "다음" 버튼이 활성화 되는 문제가 있습니다. 제가 수정했으니, [f86bfbb](https://github.com/Care-Giver/CareGiver/pull/149/commits/f86bfbb0075372e2dbe64519c3c62d3f347a83b8) 커밋 참고해주세요. <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/70505699/263504323-7f68a2a8-f158-4b18-8cb3-7642fcbf6be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTMxMjE0MDcsIm5iZiI6MTY5MzEyMTEwNywicGF0aCI6Ii83MDUwNTY5OS8yNjM1MDQzMjMtN2Y2OGEyYTgtZjE1OC00YjE4LThjYjMtNzY0MmZjYmY2YmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMwODI3VDA3MjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDM2ZWYzZGRkODg4MTU2MTBjNTljYWE4MmNmYWY3NDAzNzEyNTBlNzY1NTRlNzM3ZDg1MTZlZGNkZDZhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EMS6eyAYZ6nI4gZicwAZQPsN51NxbNNoLd8iDJmZggk">

네 바로 확인하겠습니다. 감사합니다.

2023-09-05 11:46 UTC, merged