Mvp 68
Care-Giver/CareGiver pull request #179
Opened 2024-01-21 07:10 UTC by minSsan

## 작업 내역
- `PaymentFeeInfo` 컴포넌트 추가
    - calculate time 모듈 추가
- `payment-screen.controller.ts` 파일 내 `useCalculator` 수정
    - payment adaptor 적용 (`/screens/_CLIENT/pay-stack/payment/payment-adaptor.ts`)

## TODO
- 반려동물 추가금액 시간 표시 (디자인 변경 필요)
- 시간/날짜별 추가 금액 표시
- 할인쿠폰 적용

2024-01-21 07:37 UTC, hojkim77 reviewed
저도 작업, 기능졀 커밋하는 습관을 들여야한다는 걸 느꼈습니다. 전체적으로 진행한 작업을 알아보기 수월했습니다. :)
기능을 모듈화하는 코드 잘 보았습니다.

2024-01-21 07:37 UTC, hojkim77 commented on app/components/payment-fee-info/payment-fee-info.tsx
> +  //! 더 좋은 방법 없을까? - 굳이 똑같은 값을 배열로 여러개씩 저장하는 방식이 비효율적으로 보임
객체가 담긴 배열인 petTypeExtraFee이군요. 소, 중, 대 순서로 객체가 들어오고 이 값을 ui에서만 사용한다면 변수로 각각 다시 선언하지 않고 직접 사용할 수 없을까요?

2024-01-21 09:47 UTC, smnchoi requested changes

2024-01-21 09:47 UTC, smnchoi commented on app/components/payment-fee-info/payment-fee-info.tsx
> +        <PreReg16 text={`${serviceFee.toLocaleString()}원`} color={SUB_HEAD_LINE} />
@minSsan 
예전 react-native 에서는 안드로이드에서 String.toLocaleString() 메서드가
제대로 동작하지 않는 문제가 있었습니다. 지금은 해결되었으나 아직도 프로젝트 내에서 많은 부분에서 
String.toLocaleString() 대신 price() 함수를 사용하고 있습니다. 통일성을 위해서
`app/utils/format.ts` 파일 내에 있는 price() 함수를 import 해서 대체 해주세요 :)

2024-01-21 09:47 UTC, smnchoi commented on app/components/payment-fee-info/payment-fee-info.tsx
> +  totalExtraFee: number
@minSsan 
혼동을 피하기위해 total 이라는 단어는 한 번만 사용하는 것이 좋을 것 같습니다.
totalFee 에서 이미 total 이 사용 중이므로, `totalExtraFee` 대신 
**`petTypeExtraFeeSumByTime`** 으로 프로퍼티 네임 전부 수정해주세요.

주석도 수정해주세요.
```
 /**
   * 반려동물 추가금액 총합. (서비스 시간 값이 곱해진 값.)
   */
  ```

2024-01-21 09:47 UTC, smnchoi commented on app/screens/_CLIENT/pay-stack/payment/payment-adaptor.ts
> +export class PaymentAdaptor {
@minSsan 
추후 프로젝트에서 자주 사용될 `ResponseAdaptor` 와 구분 짓기 위해
클래스 이름을 **`PaymentRequestAdaptor`** 로 변경해주세요 :)

2024-01-21 09:47 UTC, smnchoi commented on app/services/axios/payment-calculate.ts
> +  petType: "Small" | "Medium" | "Large"
@minSsan 
`app/services/axios/types/creches.visitings.common.types.ts`
경로에 있는 `HandleType` enum 으로 대체해주세요 :)

2024-01-21 09:47 UTC, smnchoi commented on app/screens/_CLIENT/pay-stack/payment/payment-screen.controller.ts
> +        key === "visiting" ? calculateHour(selectedTime) : calculateDay(selectedTime)
@minSsan 
`date-fns` 패키지의 `differenceInDays`, `differenceInDays` 메서드를 사용하는 것이 나을 것 같습니다. :)
https://date-fns.org/v3.3.0/docs/differenceInHours
https://date-fns.org/v3.3.0/docs/differenceInDays

2024-01-21 09:49 UTC, smnchoi commented on app/components/payment-fee-info/payment-fee-info.tsx
> +  //! 더 좋은 방법 없을까? - 굳이 똑같은 값을 배열로 여러개씩 저장하는 방식이 비효율적으로 보임
@minSsan @hojkim77 
## lodash.reduce 메서드를 사용하면 하나의 객체로 정리할 수 있습니다.
```ts
import _ from "lodash"
...
  type SizeFee = {
    Small: {
      number: number // 마리 수
      fee: number // 사이즈 추가 가격
    }
    Large: {
      number: number
      fee: number
    }
    Medium: {
      number: number
      fee: number
    }
  }

  const sizeFee: SizeFee = _.reduce(
    petTypeExtraFee,
    (res, item) => {
      const petType = item.petType
      if (!res[petType]) {
        res[petType] = { number: 0, fee: 0 }
      }
      res[petType].number++
      res[petType].fee = item.extraFee
      return res
    },
    {},
  )
// 예시)
// sizeFee = {
//     Small: { number: 2, fee: 1000 },
//     Large: { number: 3, fee: 5000 },
//     Medium: { number: 1, fee: 2000 }
//   }
 ```

2024-01-26 23:48 UTC, smnchoi commented on ios/Podfile.lock
> +COCOAPODS: 1.12.1
@minSsan 
저희 프로젝트에서 이제부터 `cocoapod 1.14.3` 버전을 사용합니다.
 cocoapod 업데이트 해주세요 :)

2024-01-27 08:21 UTC, merged