Mvp 69 mvp 86
Care-Giver/CareGiver pull request #188
Opened 2024-02-21 12:49 UTC by hojkim77

# What is this PR? | PR 설명 🔍
- MVP-69/MVP-86에서 발생한 env파일 관련 문제를 해결하고자 분기된 브랜치입니다.
  
# Changes | 핵심 변경사항 📝
- MVP-69/MVP-86브랜치는 제거될 예정입니다.

2024-02-22 09:56 UTC, smnchoi commented on app/services/api/notion.ts
> -const NOTION_DATABASE_ID = "a453e770df8b42d78605b17565bea560"
@hojkim77  
이 커밋에서 노션 `API_KEY` 와 `DATABASE_ID` 가 유출되었습니다.
1. 새로운 노션 키를 발급해주세요.
2. 현재 정산용으로 사용중인 케어기버 노션 페이지에 새 DB 를 생성하고, 원래 기능대로 정상적으로 작동하는지 테스트해주세요.
수정된 .env 파일은 절대 git 에 흔적을 남기지 말고, 디스코드 DM 으로 제게 알려주세요.

감사합니다 :)

2024-02-22 09:58 UTC, hojkim77 commented on app/services/api/notion.ts
> -const NOTION_DATABASE_ID = "a453e770df8b42d78605b17565bea560"
이 부분을 놓쳤네요,, 확인해주셔서 감사합니다. 바로 작업해두겠습니다.

2024-02-23 10:25 UTC, smnchoi commented
@hojkim77 
base 브랜치를 기존 develop 브랜치에서, release/0.0.2 브랜치로 변경하여 merge 하겠습니다.

2024-02-23 11:26 UTC, smnchoi commented
@hojkim77 
iOS 빌드 이후, 앱 실행시 다음과 같은 에러가 발생합니다.
프로젝트 최상위 경로에 `.env` 파일은 추가 한 상태입니다.
안드로이드에서는 괜찮은 것 같네요 🤔
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/045694f6-e9d2-4c12-96d6-7d78a1daba64)

2024-02-23 11:48 UTC, smnchoi requested changes

2024-02-23 11:48 UTC, smnchoi commented on app/screens/cg-request-earning/cg-request-earning-screen.tsx
> +            "알 수 없는 이유로, 계좌 조회에 실패하였습니다. 입력한 정보를 다시 확인해주세요.",
@hojkim77 
에러 메시지를 보다 더 자세하게 적어주세요.
항상 사용자 입장을 고려해서 개발을 진행해주세요.
**"입력하신 예금주명과 일치하는 계좌번호가 아닙니다."** 로 수정해주세요.
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/10e25afb-5c6f-456a-817f-7cbecfe1e6d4)

2024-02-23 11:48 UTC, smnchoi commented on app/components/payment-list/payment-list.tsx
> +        const convertedServiceType = item.serviceType === "Visiting" ? "방문 펫시팅" : "위탁 펫시팅"
@hojkim77 
"Visiting" 왜 캐피탈 V 인지 이해가 안가네요. 지우님께 문의 남겼습니다.
참고: 
 https://discord.com/channels/1137734002258755654/1208236608638292029/1210553480918339584

2024-02-23 11:48 UTC, smnchoi commented on app/services/api/payment.ts
> +  serviceType: string
@hojkim77 
string 대신 이미 기존에 있는 `ServiceType` 타입 변수를 사용해주세요.

2024-02-25 13:44 UTC, minSsan requested changes

2024-02-25 13:44 UTC, minSsan commented on app/screens/cg-request-earning/cg-request-earning-screen.tsx
> +  //       client_secret: "b4c379b8-eb28-4083-b0e4-a59961752480",
이 값들도 발급받은 key 값인 것 같은데, 마찬가지로 env 파일에 보관하는 것이 나을 것 같습니다 ..!

2024-03-02 11:41 UTC, smnchoi commented
@hojkim77 
merge base 브랜치를`release/0.0.3` 으로 변경하였습니다.
앞으로는 PR 생성시, merge base 브랜치를 `develop` 대신,
스프린트의 목표 release 버전에 맞는 브랜치를 merge base 브랜치로 설정해주세요 :)
스프린트가 끝나면, 제가 해당 release 브랜치와 develop 브랜치를 sync 하겠습니다.

2024-03-05 08:36 UTC, smnchoi commented
> @hojkim77 iOS 빌드 이후, 앱 실행시 다음과 같은 에러가 발생합니다. 프로젝트 최상위 경로에 `.env` 파일은 추가 한 상태입니다. 안드로이드에서는 괜찮은 것 같네요 🤔 ![image](https://private-user-images.githubusercontent.com/70505699/307306010-045694f6-e9d2-4c12-96d6-7d78a1daba64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mjc5ODUsIm5iZiI6MTcwOTYyNzY4NSwicGF0aCI6Ii83MDUwNTY5OS8zMDczMDYwMTAtMDQ1Njk0ZjYtZTlkMi00YzEyLTk2ZDYtN2Q3OGExZGFiYTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA4MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlZjVmYmU4ZWMxMTliNjgxYjg3MzVjZGRjY2NmYWQ3YTMwYjdmMGIzZmJlNTYyZDI2OTZhNDliODA4NTk4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HBRMH918nVfz4Yx5ItPhfJCR1s16UdM3vBIlAVtRuQQ)

# @hojkim77 위 문제는 캐시 이슈였습니다. 무시해주세요 :)
다음과 같이 `node_modules` 를 재설치하고 캐시를 지우니까 해결되었습니다. 
`rm -rf node_modules; yarn install; yarn start-metro --reset-cache`

(참고 바랍니다 @minSsan )

2024-03-06 07:34 UTC, smnchoi requested changes

2024-03-06 07:34 UTC, smnchoi commented on app/screens/cg-request-earning/constant.ts
> +export const bankCodeList = {
@hojkim77 자료의 출처를 적어주세요 :)

2024-03-06 07:56 UTC, hojkim77 commented on app/screens/cg-request-earning/constant.ts
> +export const bankCodeList = {
https://gist.github.com/eces/25119bbebd2305f3dec2ce779846d279
입니다.
지금 확인해보니, 카카오뱅크가 제외되어있어 추가 필요합니다.

2024-03-10 09:14 UTC, smnchoi commented on app/screens/cg-request-earning/constant.ts
> +  "090": "카카오뱅크",
@hojkim77 
추가해주셔서 감사합니다.

아무래도 이 데이터의 출처가 이곳인 곳 같네요:
https://faq.portone.io/1dae5145-1feb-4ef2-87ef-4b0e8a984945

다음부터는, 변수 `bankCodeList` 상단에 JSDOC 문법에 맞게 설명을 추가해주세요.
이렇게요:
```ts
/**
 * 포트원 문서상에 있는 가상계좌 목록입니다.
 * 출처: https://faq.portone.io/1dae5145-1feb-4ef2-87ef-4b0e8a984945
 */
export const bankCodeList = { 
...
```

이번에는 제가 추가하도록 하겠습니다.
다음부터는 유의해주세요 :)

2024-03-10 09:19 UTC, merged