Mvp 73
Care-Giver/CareGiver pull request #197
Opened 2024-03-06 07:53 UTC by hojkim77

# What is this PR? | PR 설명 🔍
댓글 조회, 작성, 수정에 대한 작업을 진행했습니다.
관련 스토리: https://caregiver-frontend.atlassian.net/browse/MVP-73
  
# Changes | 핵심 변경사항 📝
- 댓글 조회, 작성, 수정에 대한 api를 작성했습니다.
- 댓글 관련 스크린에 대해 더미데이터를 실제 데이터로 교체하는 작업을 진행했습니다.
  - 해당 작업 중 스크린 헤더를 교체하는 작업이 진행되었습니다. (AllCommentsScreen, WritingCommentScreen)
  - 해당 작업 중 각 스크린 네비게이션 관련 타입수정과 라우트 추가가 있었습니다.
- 댓글 작성과 수정 스크린을 한 스크린에서 관리하도록 WritingCommentScreen을 리팩토링했습니다.

# Help me | 도와주세요 🤦🏻‍♂️
위 핵심 변경사항 중 <- 댓글 작성과 수정 스크린을 한 스크린에서 관리하도록 WritingCommentScreen을 리팩토링했습니다.>에서 api호출 후, 네비게이션 처리(pop, replace ...)에서 적절한 아이디어가 추가로 필요합니다.

2024-03-11 10:23 UTC, smnchoi requested changes

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/caregiver-detail-information-screen/caregiver-detail-information-screen.tsx
> +import { BottomSheetBackdrop, BottomSheetFooter, BottomSheetModal } from "@gorhom/bottom-sheet"
@hojkim77 `BottomSheetFooter` 는 사용되고 있지 않습니다. import 에서 제외시켜 주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/components/comment/comment.tsx
> +import bottomSheetModal from "@gorhom/bottom-sheet/lib/typescript/components/bottomSheetModal"
@hojkim77 사용되고 있지 않습니다. import 에서 제외시켜 주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/components/comment/comment.tsx
>  import { alertModal } from "../../utils/alert-modal"
@hojkim77 사용되고 있지 않습니다. import 에서 제외시켜 주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/components/comment/comment.tsx
> +export const Comment = forwardRef((props: CommentProps) => {
@hojkim77 `Comment` 컴포넌트는 `ref` 객체를 prop 으로 사용하고 있지 않습니다. 따라서, `forwardRef` 는 불필요합니다.
리렌더링 최적화를 위해서 `Memoization` 을 의도하신 거라면, `obeserver` 를 사용해주세요.

2024-03-11 10:23 UTC, smnchoi commented on app/components/comment/comment.tsx
> +        {/* //TODO 백엔드측 대응 후 이미지, 닉네임 교체 필요 */}
@hojkim77 해결되었다면, 이 주석은 이제 지워주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/components/comment/comment.tsx
> +            if (userId !== __commentator__.id) setIsUserComment(false)
@hojkim77 
```ts
if (userId === __commentator__.id) setIsUserComment(true)
if (userId !== __commentator__.id) setIsUserComment(false)
```
이 두 줄은 다음과 같이 한번에 간소화 할 수 있습니다:

```ts
setIsUserComment(userId === __commentator__.id)
```

2024-03-11 10:23 UTC, smnchoi commented on app/services/api/comment.ts
> +export interface CommentColmns {
@hojkim77 오타가 있는 것 같습니다. `CommentColumns` 로 수정해주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> +import { allComments } from "./dummy-data"
@hojkim77 `allComments` 는 import 에서 제외시켜주세요. dummy-data 파일도 삭제해주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> +  }
@hojkim77 if 문을 두개로 분리하여 작성하신 이유는, 아마도 [Guard Clauses](https://blog.webdevsimplified.com/2020-01/guard-clauses/) 적용 예시를 오해하신 것 같습니다.

예외 상황을 if 블럭과 return 으로 처리하고,
정상 상황은 if 블럭 없이 작성하시면 됩니다

Guard Clauses 를 올바르게 사용하면 다음과 같이 다시 작성할 수 있습니다:
```ts
  const onPressCommentOption = () => {
    if (!isUserComment) {
      alertModal("개발중 🏗️", "답글 기능은 개발 중 입니다.")
      return
    }

    bottomSheetModalRef.current.close()
    navigate("writing-comment-screen", {
        updateOrCreate: "update",
        commentId: selectedCommentId,
        defaultComment: selectedComment,
    })
  }
```

2024-03-11 10:23 UTC, smnchoi commented on app/services/api/comment.ts
> +}
@hojkim77
1.
`getVisitingComments` 메서드가 사용되는 문맥을 생각해보니, `isSuccess: false` 인 경우, `visitingComments: []` 이어야 앱이 올바르게 작동합니다.
`all-comments-screen` 애서 `comments?.length` 가 사용되는 것을 근거로, comments 는 적어도 "빈 어레이 []" 타입이어야 합니다.


2.
`reason` 을 return 하는 대신, `alertModal` 메서드를 `getVisitingComments` 메서드 내부에 사용해주세요.

위 피드백에 맞게 return 값을 수정해주세요. 
그에 맞게, `GetCommentsInputResult` type 도 알 맞게 수정해주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/services/api/comment.ts
> +}
@hojkim77
마찬가지로,
`reason` 을 return 하는 대신, `alertModal` 메서드를 `updateVisitingComment` 메서드 내부에 사용해주세요.

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/caregiver-detail-information-screen/caregiver-detail-information-screen.tsx
> +        }
@hojkim77
`res.isSuccess` 값에 상관없이, 항상 `setComments(res.visitingComments)` 해주세요.
(`api/comment.ts` 파일 내, `getVisitingComments` 피드백과 함께 봐주세요.)

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> +
@hojkim77
1. UI 영역이 너무 작아서, 유저에게 터치 피드백이 있는게 나을 것 같습니다. `TouchableOpacity` 로 교체해주세요.

2. 터치 영역이 너무 작습니다. [`hitSlop`](https://reactnative.dev/docs/touchablewithoutfeedback#hitslop) prop 을 사용해주세요. 
```ts 
hitSlop={4}
```

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/caregiver-detail-information-screen/caregiver-detail-information-screen.tsx
>  import { commentsDummy } from "../all-comments-screen/dummy-data"
@hojkim77 
`dummy-data` 파일 삭제해주세요 :)

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/writing-comment-screen/writing-comment-screen.tsx
> +      />
@hojkim77
`wordsCount` prop 을 `ableToRegister`<boolean> 으로 교체하는게 더 나을 것 같습니다.
`WritingCommentScreenHeader` 내부에서 `wordsCount` 값은 0 보다 큰 값인지 아닌지를 판단합니다. 이 외에 다른 사용도는 없습니다.

SOLID 원칙에 의하면, 자식 컴포넌트는 최대한 가능한 간단하게 설계해야 합니다.
따라서, 다음과 같이 수정하는게 `WritingCommentScreenHeader` 의 복잡도를 감소시킵니다:

```tsx
<WritingCommentScreenHeader
    title={"댓글 작성"}
    onPress={onPressSubmit}
    ableToRegister={wordLength > 0}
/>
```

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/writing-comment-screen/writing-comment-screen.tsx
> +  const [wordLength, setWordLength] = useState<number>(0)
@hojkim77
# 리액트 주니어 개발자들이 정말 많이 하는 실수입니다. 호중님께서는 이번 기회에 확실하게 교정하시길 바랍니다.

1. `wordLength` 는 결국 `comment` 에 의존적입니다.
2. `comment.length` 가 결국 `wordLength` 입니다.
3. `comment` 가 이미 state 로 관리되고 있는데, `wordLength` 도 state 로 관리할 필요가 없습니다.
4. 오히려 이렇게 서로 의존적인 두 state 를 설계하게 되면, "불필요한 리렌더링"이 발생합니다. (setComment -> comment 바뀜 -> 리렌더링, setWordLength -> wordLength 바뀜 -> 리렌더링)

즉, wordLength 는 state 가 아니라, 그냥 JS 변수로 정의하면 됩니다.
```ts
const wordLength = comment.length
```

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/writing-comment-screen/writing-comment-screen.tsx
> +  }
@hojkim77
여기서는 `else if` 가 더 가독성이 나을 것 같네요 :)

```ts
...
//* 해당 스크린으로 들어온 경로(수정 or 작성)에따라 기능을 달리합니다.
const onPressSubmit = async () => {
    let response;

    if (updateOrCreate === "create") {
        response = await createVisitingComment({
            userId: userDetail.id,
            visitingId: visitingId,
            desc: comment,
            isPrivate: false,
        })
    } else if (updateOrCreate === "update") {
        response = await updateVisitingComment(commentId, { desc: comment, isPrivate: false })
    }

    response && response.isSuccess && navigation.pop(2)
}
...
```

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/writing-comment-screen/writing-comment-screen.tsx
> +      <PreMed20 style={{ marginLeft: 8 }}> {title}</PreMed20>
@hojkim77
```tsx
<PreMed20 ml={8} text={title}/>
```

2024-03-11 10:23 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/writing-comment-screen/writing-comment-screen.tsx
> +        onPress={onPress}
@hojkim77
아무 내용을 입력하지 않았어도, "등록"버튼이 클릭 가능하고, 빈 메시지로 댓글이 생성되네요.
이건 의도와는 다른 기능이므로, 통제되어야 합니다.

`disabled` prop 을 사용하세요:

```tsx
<Pressable
    onPress={onPress}
    disabled={!ableToRegister}
    ...
/>

```

2024-03-14 10:07 UTC, smnchoi commented
@hojkim77 
펫시터 상세보기 스크린에서 댓글들 "최신순" 으로 정렬해야 합니다.
현재는 "생성순(오래된순)"으로 정렬되어 있습니다.

참고:
https://discord.com/channels/1137734002258755654/1211631162796286053/1216752771064401920

2024-03-14 12:05 UTC, hojkim77 commented on app/components/comment/comment.tsx
> +export const Comment = forwardRef((props: CommentProps) => {
bottomSheetModalRef라는 ref를 갖고있습니다. ref를 컴포넌트에 prop으로 넘겨줄 땐 forwardRef로 해당 컴포넌트를 감싸는 것이 규칙으로 알고있어 적용시켰었습니다.
다시 한 번 피드백 부탁드립니다!

2024-03-15 09:42 UTC, smnchoi requested changes

2024-03-15 09:42 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> -    }
@hojkim77 
if 블럭 내부에서 `return` 키워드 뺴먹었습니다.

2024-03-15 09:52 UTC, smnchoi commented on app/components/comment/comment.tsx
> +export const Comment = forwardRef((props: CommentProps) => {
> bottomSheetModalRef라는 ref를 갖고있습니다. ref를 컴포넌트에 prop으로 넘겨줄 땐 forwardRef로 해당 컴포넌트를 감싸는 것이 규칙으로 알고있어 적용시켰었습니다. 다시 한 번 피드백 부탁드립니다!

@hojkim77 
그렇군요. 제가 놓쳤네요.
하지만 그 부분과 관련된 코드를 다시보니,
```ts
          onPress={() => {
            //TODO 유저 id에 따라 수정 및 답글 기능 추가
            //alertModal("개발중 🏗️", "댓글 편집 기능은 개발 중 입니다.")
            if (userId === __commentator__.id) setIsUserComment(true)
            if (userId !== __commentator__.id) setIsUserComment(false)
            setSelectedCommentId(id)
            setSelectedComment(desc)
            bottomSheetModalRef.current.present()
          }}
  ```
 이 부분은 SOLID 원칙에 위배 됩니다. 
`<Comment />` 컴포넌트는 "댓글 UI 렌더링" 이라는 "단일 책임 원칙 (Single-responsibility principle)" 을 준수해야 합니다.
- useId 와 __commentator__.id 를 비교하는 것
- isUserComment 인지 아닌지 판단하는 것
- 바텀시트를 여는 것
모두 `<Comment />` 컴포넌트 내부에서 책임져야 할 것이 아니라, `onPress` prop 을 통해 컴포넌트 밖에서 처리하는 것이 더 SOLI 원칙에 맞는 설계방식입니다.

`onPress` prop 을 추가하여 위에서 언급된 로직을 모두 컴포넌트 밖으로 뺴주세요.

이후, `<Comment/>` 가 쓰인 다른 곳에서도 적절하게 코드를 수정해주세요.
![image](https://github.com/Care-Giver/CareGiver/assets/70505699/6ec21dbb-5113-46f9-a26a-7dc646b63fd3)

2024-03-15 12:41 UTC, hojkim77 commented on app/components/comment/comment.tsx
> +export const Comment = forwardRef((props: CommentProps) => {
지금보니 불필요한 prop을 사용했네요. 짚어주셔서 감사합니다 :)

2024-03-18 10:18 UTC, smnchoi requested changes

2024-03-18 10:18 UTC, smnchoi commented on app/components/comment/comment.tsx
> +  onPress?: () => void
@hojkim77 
맥락을 보아하니,
onPress 는 optional 이 아니라, required prop 이 더 적절할 것 같습니다.
```ts
  onPress: () => void
 ```
 으로 수정해주세요 :)

2024-03-18 10:18 UTC, smnchoi commented on app/components/comment/comment.tsx
>            style={{ width: 10, alignItems: "center" }}
@hojkim77 
디자인 상, `images.vertical_3_dots` 이미지가 좀 작아서, 터치영역이 너무 작을 것 같네요.
`hitSlop={4}` 추가해주시면 감사하겠습니다. 🙏🏻

2024-03-18 10:20 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> +        data={_.sortBy(comments, "createAt").reverse()}
@hojkim77 
잘 하셨습니다 :) 이제 lodash 잘 사용하시네요 ㅎㅎ
[orderBy 메서드](https://lodash.com/docs/4.17.15#orderBy)도 존재하므로, 공부하실때 참고바랍니다 :)

2024-03-22 09:07 UTC, merged

2024-04-03 08:01 UTC, smnchoi commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> +              setSelectedCommentId(item.__commentator__.id)
@hojkim77 댓글 "수정" 기능 정상적으로 작동하는지, 코드 작성하고나서 직접 테스트 해보셨나요?

2024-04-03 09:43 UTC, hojkim77 commented on app/screens/_CLIENT/caregiver-detail-stack/all-comments-screen/all-comments-screen.tsx
> +              setSelectedCommentId(item.__commentator__.id)
네 직접 테스트하며 진행했습니다.
미처 생각하지 못한 예외사항이 있던 것으로 보입니다.