MVP-1 예약신청 카드 컴포넌트 추가
Care-Giver/CareGiver pull request #93
Opened 2023-05-15 06:30 UTC by bongbong811

MVP-1 예약신청 카드 컴포넌트 추가

2023-05-15 07:24 UTC, smnchoi commented
@bongbong811
코드리뷰를 위해 앱을 실행한 모습입니다.
영묵님 환경에서 실행한 모습과 컴포넌트 디자인이 동일한가요?
혹시나해서, 확인차 여쭙습니다 🙂
[image.png](https://files.slack.com/files-pri/T035QQ6AYK0-F057R8KK318/image.png)

2023-05-15 08:02 UTC, smnchoi requested changes

2023-05-15 08:02 UTC, smnchoi commented on app/components/booking-info-card/booking-info-card.tsx
> +  name: string //클라이언트 이름
@bongbong811
prop type 에 대한 설명을 달아주신것이 훌륭합니다.
다만, // 를 통해 작성하는 대신, 
```
/**
 * [설명내용]
 */
```
형태로 작성해주세요 :)
이렇게 작성해주면, TypeScript 가 알아서 인식해서, prop 에 대한 설명을 연결해줍니다.

2023-05-15 08:02 UTC, smnchoi commented on app/components/booking-info-card/booking-info-card.tsx
> +        <PreBol14
@bongbong811
XD 디자인 상으로, Pretendard Regular 12pt 입니다.
PreReg12 컴포넌트로 대체하여 주시기 바랍니다 :)

2023-05-15 08:02 UTC, smnchoi commented on app/components/booking-info-card/booking-info-card.tsx
> +            defaultViewStyle={styles.bookgingchoicestyle}
@bongbong811
이 디자인은 `width: 46px` 이 되어야 합니다 :)

2023-05-15 08:02 UTC, smnchoi commented on app/components/booking-info-card/booking-info-card.tsx
> +            style={{ marginRight: "6%" }}
@bongbong811
`margin` 과 `padding` 은 % 값이 아닌 px 값으로 선언해주세요 :) 
정확한 값은 XD 디자인 링크에서 보실수 있습니다.

2023-05-15 08:02 UTC, smnchoi commented on app/components/booking-info-card/booking-info-card.tsx
> +  container: {
@bongbong811
XD 디자인 상으로, 컴포넌트 외곽에 그림자 효과가 적용되어있습니다.
따라서, 그림자 효과가 추가로 필요합니다 :)
다만, 이 부분은 처음 시도하시기 어려우실수 있으므로, 후속 commit 으로 제가 추가하도록 하겠습니다.

2023-05-15 08:03 UTC, smnchoi commented
@bongbong811
코드리뷰 마쳤습니다 🙂
처음 작업임에도 불구하고, 프로젝트에 기존에 있는 컴포넌트를 매우 잘 재활용하여 만들어주셨습니다. 훌륭합니다.

2023-05-15 08:05 UTC, smnchoi commented
@bongbong811
Review 로 달아드린 피드백을 반영해주세요.
동일한 브랜치 (`MVP-1/예약신청-카드`) 에서 작업해주시면 됩니다. 마찬가지로, 커밋메시지 앞에 `MVP-1`을 꼭 추가해주세요 🙂

2023-05-15 08:06 UTC, smnchoi commented on app/components/booking-info-card/booking-info-card.tsx
> +  container: {
d69448a5efb5b0becfce9011e8f85c28cb6d2b13
위 커밋에 그림자 효과 추가하였습니다 :)

2023-05-17 07:01 UTC, merged

2023-05-17 07:14 UTC, smnchoi commented
@bongbong811  실수로 merge 하신건가요?

2023-05-17 07:37 UTC, bongbong811 commented
ㅇㅏ 네네 close 하려고 했는데 merge 했네요 ㅠㅠ 의견주신 사항 수정했는데 close 시키고 새로운 pull request 날리면 될까요?!

2023-05-17 07:48 UTC, smnchoi commented
1. 이미 merge 된 pull request 는 close 시킬 수 없습니다 ,🥲
2. 우선, 수정사항 먼저 확인해보겠습니다. 
3. 만약, 추가 수정사항이 필요하다면 새로 pull request 만들어주시면 됩니다 ,🙂,

2023-05-17 07:50 UTC, bongbong811 commented
아 네네 번거롭게 해드려서 죄송합니다 ㅠㅠ 다음부터는 주의하도록 하겠습니다!

2023-05-17 07:52 UTC, bongbong811 commented
현재 추가 수정사항은 없습니다! 수정사항 보시고 추가의견 주시면 그때 수정해서 pull request 하겠습니다~

2023-05-17 08:58 UTC, smnchoi commented
@bongbong811 몇가지 수정사항이 있어서 제가 반영하였습니다. [새로운 pull request](https://github.com/Care-Giver/CareGiver/pull/97) 에서 내역을 보실 수 있으니, 학습을 위해서 봐주시길 바랍니다 🙂
고생하셨습니다!