Mvp 6/결제완료 모달 컴포넌트 통합
Care-Giver/CareGiver pull request #98
Opened 2023-05-19 08:26 UTC by hojkim77

MVP -6/모달 컴포넌트 통합  ->  Add : 모달 컴포넌트 통합

2023-05-19 11:26 UTC, smnchoi approved these changes

2023-05-19 11:26 UTC, smnchoi commented on app/components/custom-modal/custom-modal.props.ts
> +  image: ImageSourcePropType,
@minSsan 좋은 피드백 주셨네요 :) 아주 적절한 type 입니다! 👍

2023-05-19 11:59 UTC, smnchoi requested changes

2023-05-19 11:59 UTC, smnchoi commented on app/screens/caregiver-detail-stack/caregiver-detail-information-screen/caregiver-detail-information-screen.tsx
>          subtitle={`케어기버가 서비스를 승인할 때까지\n잠시만 기다려주세요`}
@hojkim77 중앙정렬이 안 되어 있습니다. 원래 디자인대로 중앙정렬을 추가해주세요 :) 
이를 위해선, CustomModal 컴포넌트에 subtitleStyle porp 을 추가하고, 적용시키는 방안을 고민해보세요!

2023-05-19 11:59 UTC, smnchoi commented on app/components/custom-modal/custom-modal.tsx
>            {subtitle && <PreReg14 text={subtitle} color={BODY} style={{ marginTop: 8 }} />}
@hojkim77

```suggestion
          {subtitle && <PreReg14 text={subtitle} color={BODY} style={[{ marginTop: 8 }, subtitleStyle]} />}
```

2023-05-20 07:21 UTC, hojkim77 commented
@smnchoi 수민님 질문이 있습니다!
주신 피드백 내용 수정중에 의문점이 생겨서요. subtitle 의 style prop에 `style={{ marginTop: 8, textAlign:"center" }}` 와 같이 직접적으로 스타일을 주는 방식 대신에 subtitleStyle porp으로 받아와야하는 이유가  따로 있을까요? 모달창 디자인에서는 subtitle이 대부분 가운데정렬을 필요로하는 디자인일것 같아 질문드렸습니다!

감사합니다🙂

2023-05-20 11:20 UTC, smnchoi commented
@hojkim77 좋은 질문입니다 🙂
이런경우에는 말씀해주시는 것처럼 직접적으로 스타일링을 주어도됩니다.
하지만, 직접적인 스타일링 와에도, subtitleStyle prop 도 같이 추가해주는 것이 컴포넌트의 확장성 측면에서 더  좋습니다!
제가 예를 들기위해 곧 새 커밋을 올려드리겠습니다 🙂

2023-05-20 11:33 UTC, smnchoi commented on app/components/custom-modal/custom-modal.tsx
> +  const $subtitleStyle = Object.assign({}, styles.subtitle, subtitleStyle)
@hojkim77  이처럼 subtitleStyle prop 을 활용하여, 스타일링을 더 확장할 수 있게 됩니다 :)

Object.assgin({}) 으로 스타일링을 확장한 코드는
`app/components/time-picker/time-picker.tsx`
`app/components/service-type-indicator-header/service-type-indicator-header.tsx`
위 파일들 보시면 더 참고하실 수 있습니다 :)

2023-05-20 13:54 UTC, hojkim77 commented
@smnchoi
피드백해주신 내용 머지 후 magin값 약간 수정 후 커밋했습니다!
수정이 더 필요하다면 피드백 주시면 감사하겠습니다.

추가적으로, 이러한 component를 만들게 될 때 style에 대해서 어떤 때에는 tag에 직접 할당하고 어떤 때에는 style 또는 prop으로 받아오게되는데, 이는 어떠한 기준으로 보아야하는지 알고싶습니다!

피드백과 더불어 항상 많은 부분 알려주셔서 감사합니다☺️

2023-05-20 13:56 UTC, smnchoi commented
_tag에 직접 할당 _한다는게, 컴포넌트에 style prop 을 통해서
인라인으로 스타일 주는걸 말씀하시는건가요?

인라인 코드가, Prettier 포맷팅시 두 줄 이상 길어지면
StyleSheet 으로 생성한 style 객체로 따로 빼서 관리합니다 🙂

2023-05-20 14:34 UTC, merged