Mvp 15/펫시터 훈련사 등록하기 버튼
Care-Giver/CareGiver pull request #99
Opened 2023-05-25 06:18 UTC by hojkim77

내정보의 펫시터/훈련사 등록하기 버튼입니다.
- prop
img: 양자택일인지라 조건문으로 component 내에서 받아왔습니다!
subtitle: 개행처리 될 것을 감안하여 textbox의 width를 설정하지 않았습니다.
onPress: 우선 jira의 요구사항에 맞춰 alert()만 전달하였습니다.

2023-05-25 10:07 UTC, smnchoi requested changes

2023-05-25 10:07 UTC, smnchoi commented on app/components/cg-service-choice-button/cg-service-choice-button.tsx
> +import { CgServiceChoiceButtonProps } from "./cs-service-choice-button.props"
@hojkim77 
파일명에 실수가 있는 듯 하네요.
cs-service-choice-button.props 가 아니라 c**g**-service-choice-button.props
로 수정부탁드립니다 :)

2023-05-25 10:07 UTC, smnchoi commented on app/components/cg-service-choice-button/cg-service-choice-button.tsx
> +        resizeMode="stretch" //! DO NOT REMOVE THIS
@hojkim77 
왜 지우면 안되는지, 이유도 주석으로 써주세요 :)

2023-05-25 10:07 UTC, smnchoi commented on app/components/cg-service-choice-button/cs-service-choice-button.props.ts
> +  onPress: () => any
@hojkim77 
onPress: () => void 
로 수정부탁드립니다.

2023-05-25 10:07 UTC, smnchoi commented on app/screens/temp/temp-screen.tsx
> +        <CgServiceChoiceButton title="펫시터 등록하기" subtitle={`산책, 간식 주기 등 펫을\n 돌봐주는 서비스입니다.`}
@hojkim77 
`산책, 간식 주기 등 펫을\n돌봐주는 서비스입니다.`
이게 맞을 것 같습니다. :)

2023-05-25 10:07 UTC, smnchoi commented on app/screens/temp/temp-screen.tsx
> +        onPress={onPress}/>
@hojkim77 
코드 formatting 이 안되어있는것 같은데, VSCode 에 Prettier 켜져 있나요?
커밋 이전에 항상 Prettier 를 사용하여 formatting 후 커밋해주세요 :)

2023-05-25 10:44 UTC, hojkim77 commented
잔실수가 많네요,,
바로 수정해서 올리겠습니다.

2023-05-25 22:39 UTC, smnchoi commented
@hojkim77
매우 빠른속도로 저희 프로젝트에 적응해주시고 계셔서 감사할 따름이네요 ☺️ 훌륭합니다 :+1: 
이번 작업이 끝나면, 케어기버 서버 DB 셋업을 안내해드리겠습니다! 추후, API 사용 및 테스트를 위해선 DB 접근이 필요합니다 🙂

2023-05-26 03:12 UTC, hojkim77 commented
@smnchoi
네 감사합니다😀
수정 완료했습니다!

2023-05-26 04:07 UTC, smnchoi commented
감사합니다 :) 퇴근후 리뷰하겠습니다 :+1:

2023-05-26 13:17 UTC, smnchoi approved these changes

2023-05-26 13:17 UTC, smnchoi commented on app/components/cg-service-choice-button/cg-service-choice-button.props.ts
> +  title: "펫시터 등록하기" | "훈련사 등록하기"
@hojkim77 
image 를 title 을 기준으로 조건을 판단하기 때문에
보다 더 안전하게, 명시적으로 type 을 수정하였습니다.

2023-05-26 13:17 UTC, smnchoi commented on app/components/cg-service-choice-button/cg-service-choice-button.tsx
> +  const imageSelector = () => {
@hojkim77 
ternary 로 잘 구현해주셨으나,
2번 이상 중첩된 ternary 는 되려 code readability 를 저하시킵니다.
따라서, 보다 더 readable 한 코드로 바꾸었습니다.

2023-05-26 13:17 UTC, merged

2023-05-26 13:21 UTC, smnchoi commented
@hojkim77 코드 리뷰 완료하였습니다.
피드백용 커밋이 있으니, review 확인 부탁드립니다 🙂
이번 업무 성공적으로 잘 해주셔서 감사드립니다.
다음 업무는 스타일링 뿐만 아니라, 케어기버 API를 사용하는 업무가 주어질예정입니다. 내일 회의때 뵙겠습니다 🙂

2023-05-26 13:35 UTC, hojkim77 commented
@smnchoi 감사합니다 😀 
수정된 코드도 다시 보고 공부하겠습니다!
내일 뵙겠습니다 🙂